In [2]:
import orca
import datasources
import variables
import models

Model template is: zone. Operating on zones with zone_id.

In [2]:
orca.run(['build_networks'])

Running step 'build_networks'
Number of nodes is 23717.
Number of edges is 26388.
Precomputing network for distance 40000.
Network precompute starting.
Network precompute done.
Time to execute step 'build_networks': 8.87 s
Total time to execute iteration 1 with iteration value None: 8.87 s

In [7]:
orca.get_table('zones').local_columns

['x',
 'y',
 'res_rent',
 'res_value',
 'acres',
 'residential_unit_capacity',
 'employment_capacity',
 'node_id']

In [3]:
zones = orca.get_table('zones').to_frame()

Disaggregating high_income_hh_20km to zones from nodes
Calculating high_income_hh_20km
Calculating std_workers of households for zones
Disaggregating low_income_hh_1500m to zones from nodes
Calculating low_income_hh_1500m
Calculating mean_year_built of residential_units for zones
Disaggregating post2010_du_1500m to zones from nodes
Calculating post2010_du_1500m
Disaggregating jobs_1500m_61 to zones from nodes
Calculating jobs_1500m_61
Calculating proportion year_built 2011 for zones
Calculating number of residential_units for zones
Disaggregating jobs_1500m_71 to zones from nodes
Calculating jobs_1500m_71
Disaggregating low_income_hh_5000m to zones from nodes
Calculating low_income_hh_5000m
Disaggregating jobs_1500m_72 to zones from nodes
Calculating jobs_1500m_72
Calculating proportion cars 1 for zones
Calculating number of households for zones
Disaggregating population_800m to zones from nodes
Calculating population_800m
Calculating proportion cars 3 for zones
Calculating proportion cars 2 for zones
Calculating proportion sector_id 72 for zones
Calculating number of jobs for zones
Calculating proportion sector_id 71 for zones
Calculating mean_workers of households for zones
Calculating proportion persons 5 for zones
Disaggregating post2010_du_5000m to zones from nodes
Calculating post2010_du_5000m
Calculating ratio of jobs to households for zones
Calculating proportion tenure 2 for zones
Calculating proportion year_built 1965 for zones
Calculating proportion aggr_sector_id 0 for zones
Disaggregating jobs_3000m_3133 to zones from nodes
Calculating jobs_3000m_3133
Disaggregating post2000_du_800m to zones from nodes
Calculating post2000_du_800m
Disaggregating post2000_du_1500m to zones from nodes
Calculating post2000_du_1500m
Disaggregating jobs_5000m_56 to zones from nodes
Calculating jobs_5000m_56
Disaggregating jobs_5000m_54 to zones from nodes
Calculating jobs_5000m_54
Disaggregating jobs_5000m_55 to zones from nodes
Calculating jobs_5000m_55
Disaggregating jobs_5000m_52 to zones from nodes
Calculating jobs_5000m_52
Disaggregating jobs_5000m_53 to zones from nodes
Calculating jobs_5000m_53
Disaggregating jobs_5000m_51 to zones from nodes
Calculating jobs_5000m_51
Disaggregating du_400m to zones from nodes
Calculating du_400m
Disaggregating own_singlfam_du_1500m to zones from nodes
Calculating own_singlfam_du_1500m
Disaggregating jobs_5000m_72 to zones from nodes
Calculating jobs_5000m_72
Disaggregating population_20km to zones from nodes
Calculating population_20km
Disaggregating high_income_hh_5000m to zones from nodes
Calculating high_income_hh_5000m
Disaggregating jobs_5000m to zones from nodes
Calculating jobs_5000m
Calculating proportion year_built 2005 for zones
Disaggregating ave_workers_1500m to zones from nodes
Calculating ave_workers_1500m
Disaggregating jobs_1500m_4445 to zones from nodes
Calculating jobs_1500m_4445
Calculating proportion children 1 for zones
Calculating proportion children 3 for zones
Calculating proportion year_built 1995 for zones
Disaggregating jobs_1500m_62 to zones from nodes
Calculating jobs_1500m_62
Calculating proportion children 4 for zones
Disaggregating post2010_du_3000m to zones from nodes
Calculating post2010_du_3000m
Disaggregating ave_children_1500m to zones from nodes
Calculating ave_children_1500m
Calculating proportion persons 3 for zones
Calculating proportion aggr_sector_id 5 for zones
Disaggregating households_15km to zones from nodes
Calculating households_15km
Calculating proportion sector_id 61 for zones
Calculating proportion sector_id 62 for zones
Disaggregating jobs_1500m_agg3 to zones from nodes
Calculating jobs_1500m_agg3
Calculating proportion cars 5 for zones
Disaggregating jobs_1500m_agg1 to zones from nodes
Calculating jobs_1500m_agg1
Disaggregating jobs_1500m_agg0 to zones from nodes
Calculating jobs_1500m_agg0
Disaggregating ave_cars_1500m to zones from nodes
Calculating ave_cars_1500m
Disaggregating jobs_1500m_agg5 to zones from nodes
Calculating jobs_1500m_agg5
Calculating proportion cars 4 for zones
Disaggregating jobs_5000m_23 to zones from nodes
Calculating jobs_5000m_23
Disaggregating jobs_5000m_22 to zones from nodes
Calculating jobs_5000m_22
Disaggregating jobs_5000m_21 to zones from nodes
Calculating jobs_5000m_21
Disaggregating jobs_1500m_agg4 to zones from nodes
Calculating jobs_1500m_agg4
Calculating median_recent_mover of households for zones
Calculating mean_income of households for zones
Calculating proportion cars 6 for zones
Calculating std_tenure of households for zones
Disaggregating households_30km to zones from nodes
Calculating households_30km
Calculating proportion cars 0 for zones
Calculating proportion workers 0 for zones
Calculating proportion workers 1 for zones
Calculating proportion workers 2 for zones
Disaggregating rnt_multifam_du_1500m to zones from nodes
Calculating rnt_multifam_du_1500m
Calculating proportion workers 4 for zones
Disaggregating ave_income_5000m to zones from nodes
Calculating ave_income_5000m
Disaggregating du_3000m to zones from nodes
Calculating du_3000m
Calculating mean_recent_mover of households for zones
Calculating mean_cars of households for zones
Calculating density of households for zones
Disaggregating jobs_5000m_81 to zones from nodes
Calculating jobs_5000m_81
Disaggregating households_10km to zones from nodes
Calculating households_10km
Disaggregating jobs_1500m_92 to zones from nodes
Calculating jobs_1500m_92
Disaggregating jobs_5000m_4849 to zones from nodes
Calculating jobs_5000m_4849
Disaggregating jobs_1500m_54 to zones from nodes
Calculating jobs_1500m_54
Calculating median_year_built of residential_units for zones
Disaggregating ave_year_built_5000m to zones from nodes
Calculating ave_year_built_5000m
Calculating median_income of households for zones
Calculating ratio of households to residential_units for zones
Disaggregating households_800m to zones from nodes
Calculating households_800m
Calculating proportion year_built 1985 for zones
Calculating mean_age_of_head of households for zones
Calculating median_children of households for zones
Disaggregating jobs_3000m_4445 to zones from nodes
Calculating jobs_3000m_4445
Disaggregating du_800m to zones from nodes
Calculating du_800m
Disaggregating jobs_30km to zones from nodes
Calculating jobs_30km
Disaggregating du_20km to zones from nodes
Calculating du_20km
Calculating proportion sector_id 92 for zones
Calculating std_year_built of residential_units for zones
Calculating sum_cars of households for zones
Disaggregating own_singlfam_du_3000m to zones from nodes
Calculating own_singlfam_du_3000m
Disaggregating jobs_400m to zones from nodes
Calculating jobs_400m
Disaggregating jobs_1500m to zones from nodes
Calculating jobs_1500m
Disaggregating jobs_5000m_61 to zones from nodes
Calculating jobs_5000m_61
Disaggregating jobs_1500m_4849 to zones from nodes
Calculating jobs_1500m_4849
Calculating median_persons of households for zones
Disaggregating ave_income_800m to zones from nodes
Calculating ave_income_800m
Calculating median_race_of_head of households for zones
Calculating density of residential_units for zones
Disaggregating households_400m to zones from nodes
Calculating households_400m
Disaggregating post2000_du_3000m to zones from nodes
Calculating post2000_du_3000m
Disaggregating jobs_3000m_agg4 to zones from nodes
Calculating jobs_3000m_agg4
Calculating median_sector_id of jobs for zones
Disaggregating jobs_5000m_92 to zones from nodes
Calculating jobs_5000m_92
Disaggregating jobs_1500m_81 to zones from nodes
Calculating jobs_1500m_81
Disaggregating households_25km to zones from nodes
Calculating households_25km
Calculating std_age_of_head of households for zones
Calculating proportion race_of_head 8 for zones
Calculating proportion race_of_head 9 for zones
Calculating median_tenure of households for zones
Disaggregating households_35km to zones from nodes
Calculating households_35km
Disaggregating jobs_1500m_agg2 to zones from nodes
Calculating jobs_1500m_agg2
Calculating proportion race_of_head 2 for zones
Calculating proportion year_built 1975 for zones
Calculating mean_children of households for zones
Calculating proportion race_of_head 1 for zones
Calculating proportion race_of_head 6 for zones
Disaggregating ave_year_built_800m to zones from nodes
Calculating ave_year_built_800m
Disaggregating own_multifam_du_3000m to zones from nodes
Calculating own_multifam_du_3000m
Calculating proportion sector_id 81 for zones
Disaggregating jobs_3000m_11 to zones from nodes
Calculating jobs_3000m_11
Calculating std_race_of_head of households for zones
Calculating proportion sector_id 3133 for zones
Calculating sum_children of households for zones
Calculating density of jobs for zones
Disaggregating households_3000m to zones from nodes
Calculating households_3000m
Disaggregating post2010_du_800m to zones from nodes
Calculating post2010_du_800m
Disaggregating jobs_1500m_3133 to zones from nodes
Calculating jobs_1500m_3133
Calculating std_building_type_id of residential_units for zones
Calculating std_income of households for zones
Calculating mean_tenure of households for zones
Disaggregating jobs_1500m_11 to zones from nodes
Calculating jobs_1500m_11
Disaggregating ave_age_of_head_1500m to zones from nodes
Calculating ave_age_of_head_1500m
Calculating proportion workers 3 for zones
Disaggregating jobs_20km to zones from nodes
Calculating jobs_20km
Disaggregating jobs_3000m_42 to zones from nodes
Calculating jobs_3000m_42
Disaggregating rnt_multifam_du_800m to zones from nodes
Calculating rnt_multifam_du_800m
Calculating median_building_type_id of residential_units for zones
Calculating sum_persons of households for zones
Calculating mean_building_type_id of residential_units for zones
Calculating std_sector_id of jobs for zones
Disaggregating own_multifam_du_1500m to zones from nodes
Calculating own_multifam_du_1500m
Disaggregating jobs_1500m_53 to zones from nodes
Calculating jobs_1500m_53
Disaggregating households_5000m to zones from nodes
Calculating households_5000m
Calculating mean_sector_id of jobs for zones
Disaggregating jobs_5000m_3133 to zones from nodes
Calculating jobs_5000m_3133
Disaggregating jobs_25km to zones from nodes
Calculating jobs_25km
Disaggregating jobs_5000m_11 to zones from nodes
Calculating jobs_5000m_11
Calculating median_workers of households for zones
Calculating mean_race_of_head of households for zones
Disaggregating ave_income_3000m to zones from nodes
Calculating ave_income_3000m
Disaggregating jobs_3000m_21 to zones from nodes
Calculating jobs_3000m_21
Disaggregating jobs_3000m_23 to zones from nodes
Calculating jobs_3000m_23
Disaggregating jobs_3000m_22 to zones from nodes
Calculating jobs_3000m_22
Calculating median_cars of households for zones
Disaggregating jobs_1500m_22 to zones from nodes
Calculating jobs_1500m_22
Disaggregating jobs_1500m_23 to zones from nodes
Calculating jobs_1500m_23
Disaggregating jobs_1500m_21 to zones from nodes
Calculating jobs_1500m_21
Disaggregating population_400m to zones from nodes
Calculating population_400m
Disaggregating households_20km to zones from nodes
Calculating households_20km
Disaggregating ave_year_built_1500m to zones from nodes
Calculating ave_year_built_1500m
Calculating proportion sector_id 22 for zones
Calculating proportion sector_id 23 for zones
Calculating sum_recent_mover of households for zones
Disaggregating jobs_10km to zones from nodes
Calculating jobs_10km
Disaggregating own_singlfam_du_800m to zones from nodes
Calculating own_singlfam_du_800m
Calculating median_age_of_head of households for zones
Calculating proportion persons 7 for zones
Disaggregating households_1500m to zones from nodes
Calculating households_1500m
Calculating proportion sector_id 54 for zones
Disaggregating rnt_singlfam_du_1500m to zones from nodes
Calculating rnt_singlfam_du_1500m
Disaggregating jobs_3000m to zones from nodes
Calculating jobs_3000m
Calculating proportion year_built 1955 for zones
Calculating proportion children 2 for zones
Calculating proportion persons 4 for zones
Disaggregating jobs_5000m_62 to zones from nodes
Calculating jobs_5000m_62
Disaggregating post2000_du_5000m to zones from nodes
Calculating post2000_du_5000m
Disaggregating jobs_5000m_agg2 to zones from nodes
Calculating jobs_5000m_agg2
Disaggregating jobs_5000m_agg3 to zones from nodes
Calculating jobs_5000m_agg3
Disaggregating jobs_5000m_agg0 to zones from nodes
Calculating jobs_5000m_agg0
Disaggregating jobs_5000m_agg1 to zones from nodes
Calculating jobs_5000m_agg1
Disaggregating high_income_hh_3000m to zones from nodes
Calculating high_income_hh_3000m
Disaggregating jobs_5000m_agg4 to zones from nodes
Calculating jobs_5000m_agg4
Disaggregating jobs_5000m_agg5 to zones from nodes
Calculating jobs_5000m_agg5
Calculating proportion recent_mover 1 for zones
Calculating proportion recent_mover 0 for zones
Calculating proportion persons 1 for zones
Calculating std_cars of households for zones
Calculating mean_persons of households for zones
Disaggregating jobs_1500m_56 to zones from nodes
Calculating jobs_1500m_56
Disaggregating jobs_1500m_55 to zones from nodes
Calculating jobs_1500m_55
Disaggregating jobs_800m to zones from nodes
Calculating jobs_800m
Disaggregating jobs_3000m_4849 to zones from nodes
Calculating jobs_3000m_4849
Disaggregating jobs_1500m_52 to zones from nodes
Calculating jobs_1500m_52
Disaggregating jobs_1500m_51 to zones from nodes
Calculating jobs_1500m_51
Calculating proportion sector_id 55 for zones
Calculating proportion persons 6 for zones
Calculating proportion sector_id 56 for zones
Calculating proportion sector_id 51 for zones
Calculating proportion persons 2 for zones
Calculating proportion sector_id 53 for zones
Calculating proportion sector_id 52 for zones
Disaggregating high_income_hh_1500m to zones from nodes
Calculating high_income_hh_1500m
Calculating proportion sector_id 4849 for zones
Disaggregating rnt_singlfam_du_800m to zones from nodes
Calculating rnt_singlfam_du_800m
Calculating sum_workers of households for zones
Calculating proportion year_built 1945 for zones
Calculating proportion aggr_sector_id 3 for zones
Calculating proportion tenure 1 for zones
Calculating proportion aggr_sector_id 1 for zones
Disaggregating jobs_5000m_71 to zones from nodes
Calculating jobs_5000m_71
Calculating proportion aggr_sector_id 4 for zones
Disaggregating low_income_hh_3000m to zones from nodes
Calculating low_income_hh_3000m
Disaggregating jobs_20km_agg3 to zones from nodes
Calculating jobs_20km_agg3
Disaggregating jobs_20km_agg2 to zones from nodes
Calculating jobs_20km_agg2
Disaggregating jobs_20km_agg1 to zones from nodes
Calculating jobs_20km_agg1
Disaggregating jobs_20km_agg0 to zones from nodes
Calculating jobs_20km_agg0
Disaggregating jobs_20km_agg5 to zones from nodes
Calculating jobs_20km_agg5
Disaggregating jobs_20km_agg4 to zones from nodes
Calculating jobs_20km_agg4
Disaggregating jobs_3000m_54 to zones from nodes
Calculating jobs_3000m_54
Disaggregating jobs_3000m_55 to zones from nodes
Calculating jobs_3000m_55
Calculating std_children of households for zones
Disaggregating du_5000m to zones from nodes
Calculating du_5000m
Disaggregating jobs_3000m_51 to zones from nodes
Calculating jobs_3000m_51
Disaggregating jobs_3000m_52 to zones from nodes
Calculating jobs_3000m_52
Disaggregating jobs_3000m_53 to zones from nodes
Calculating jobs_3000m_53
Disaggregating jobs_3000m_agg2 to zones from nodes
Calculating jobs_3000m_agg2
Disaggregating jobs_3000m_agg5 to zones from nodes
Calculating jobs_3000m_agg5
Disaggregating jobs_3000m_agg0 to zones from nodes
Calculating jobs_3000m_agg0
Disaggregating jobs_3000m_agg1 to zones from nodes
Calculating jobs_3000m_agg1
Disaggregating jobs_1500m_42 to zones from nodes
Calculating jobs_1500m_42
Disaggregating jobs_3000m_agg3 to zones from nodes
Calculating jobs_3000m_agg3
Calculating proportion sector_id 4445 for zones
Calculating proportion sector_id 42 for zones
Disaggregating jobs_40km to zones from nodes
Calculating jobs_40km
Calculating std_persons of households for zones
Calculating proportion aggr_sector_id 2 for zones
Disaggregating jobs_5000m_4445 to zones from nodes
Calculating jobs_5000m_4445
Calculating std_recent_mover of households for zones
Disaggregating jobs_35km to zones from nodes
Calculating jobs_35km
Disaggregating population_1500m to zones from nodes
Calculating population_1500m
Disaggregating rnt_singlfam_du_3000m to zones from nodes
Calculating rnt_singlfam_du_3000m
Calculating proportion children 0 for zones
Calculating proportion building_type_id 4 for zones
Calculating proportion building_type_id 1 for zones
Disaggregating households_40km to zones from nodes
Calculating households_40km
Calculating proportion building_type_id 3 for zones
Calculating proportion building_type_id 2 for zones
Calculating proportion year_built 1930 for zones
Disaggregating own_multifam_du_800m to zones from nodes
Calculating own_multifam_du_800m
Disaggregating du_1500m to zones from nodes
Calculating du_1500m
Disaggregating ave_year_built_3000m to zones from nodes
Calculating ave_year_built_3000m
Disaggregating jobs_15km to zones from nodes
Calculating jobs_15km
Disaggregating rnt_multifam_du_3000m to zones from nodes
Calculating rnt_multifam_du_3000m
Disaggregating jobs_5000m_42 to zones from nodes
Calculating jobs_5000m_42
Disaggregating ave_income_1500m to zones from nodes
Calculating ave_income_1500m

In [8]:
zones.res_value

2700300000001    159700.000000
2700300000002    159700.000000
2700300000003    159700.000000
2700300000004    144500.000000
2700300000005    174578.066914
2700300000006    175500.000000
2700300000007    208450.409836
2700300000008    208500.000000
2700300000009    176300.000000
2700300000010    196400.000000
2700300000011    211760.000000
2700300000012    223889.519651
2700300000013    216913.984674
2700300000014    190300.000000
2700300000015    248631.034483
2700300000016    235718.769716
2700300000017    180596.124031
2700300000018    186249.579832
2700300000019    189887.906977
2700300000020    215890.163934
2700300000021    238012.962963
2700300000022    217861.355932
2700300000023    246017.073171
2700300000024    220033.729216
2700300000025    259300.000000
2700300000026    259300.000000
2700300000027    267696.963124
2700300000028    307111.692308
2700300000029    330100.000000
2700300000030    238300.000000
                     ...
2716300000126    177600.000000
2716300000127    161779.011510
2716300000128    289932.094353
2716300000129    172177.622378
2716300000130    174724.579125
2716300000131    162300.000000
2716300000132    165625.409836
2716300000133    374455.511811
2716300000134    333535.294118
2716300000135    300285.995624
2716300000136    316275.074184
2716300000137    403100.787402
2716300000138    396900.000000
2716300000139    218642.790152
2716300000140    233211.306533
2716300000141    241484.215017
2716300000142    197556.497948
2716300000143    186651.360947
2716300000144    185482.604470
2716300000145    272794.845361
2716300000146    296300.000000
2716300000147    159277.003942
2716300000148    176709.355828
2716300000149    163573.061224
2716300000150    179544.444444
2716300000151    196200.000000
2716300000152    324675.944334
2717100000018    257100.000000
2717100000044    265900.000000
2717100000045    265900.000000
Name: res_value, dtype: float64

In [6]:
print len(zones.columns)
for col in zones.columns:
    print col

297
x
y
res_rent
res_value
acres
residential_unit_capacity
employment_capacity
node_id
nodes_high_income_hh_20km
std_workers
nodes_low_income_hh_1500m
mean_year_built
nodes_post2010_du_1500m
nodes_jobs_1500m_61
prop_year_built_2011
nodes_jobs_1500m_71
nodes_low_income_hh_5000m
nodes_jobs_1500m_72
prop_cars_1
nodes_population_800m
prop_cars_3
prop_cars_2
prop_sector_id_72
prop_sector_id_71
mean_workers
prop_persons_5
nodes_post2010_du_5000m
res_btype_mode4
ratio_jobs_to_households
prop_tenure_2
prop_year_built_1965
prop_aggr_sector_id_0
nodes_jobs_3000m_3133
nodes_post2000_du_800m
nodes_post2000_du_1500m
total_households
nodes_jobs_5000m_56
nodes_jobs_5000m_54
nodes_jobs_5000m_55
nodes_jobs_5000m_52
nodes_jobs_5000m_53
nodes_jobs_5000m_51
nodes_du_400m
nodes_own_singlfam_du_1500m
nodes_jobs_5000m_72
nodes_population_20km
du_spaces
nodes_high_income_hh_5000m
nodes_jobs_5000m
prop_year_built_2005
nodes_ave_workers_1500m
nodes_jobs_1500m_4445
prop_children_1
res_btype_mode1
prop_children_3
prop_year_built_1995
nodes_jobs_1500m_62
prop_children_4
nodes_post2010_du_3000m
nodes_ave_children_1500m
prop_persons_3
prop_aggr_sector_id_5
nodes_households_15km
prop_sector_id_61
prop_sector_id_62
nodes_jobs_1500m_agg3
prop_cars_5
nodes_jobs_1500m_agg1
nodes_jobs_1500m_agg0
nodes_ave_cars_1500m
nodes_jobs_1500m_agg5
prop_cars_4
nodes_jobs_5000m_23
nodes_jobs_5000m_22
nodes_jobs_5000m_21
nodes_jobs_1500m_agg4
median_recent_mover
mean_income
prop_cars_6
std_tenure
nodes_households_30km
prop_cars_0
prop_workers_0
prop_workers_1
prop_workers_2
nodes_rnt_multifam_du_1500m
prop_workers_4
nodes_ave_income_5000m
all_zones
nodes_du_3000m
mean_recent_mover
mean_cars
density_households
nodes_jobs_5000m_81
nodes_households_10km
nodes_jobs_1500m_92
nodes_jobs_5000m_4849
nodes_jobs_1500m_54
median_year_built
nodes_ave_year_built_5000m
median_income
ratio_households_to_residential_units
nodes_households_800m
prop_year_built_1985
mean_age_of_head
median_children
nodes_jobs_3000m_4445
nodes_du_800m
nodes_jobs_30km
nodes_du_20km
prop_sector_id_92
std_year_built
sum_cars
nodes_own_singlfam_du_3000m
nodes_jobs_400m
nodes_jobs_1500m
nodes_jobs_5000m_61
nodes_jobs_1500m_4849
median_persons
jobs
nodes_ave_income_800m
rnt_multifam_post2010
median_race_of_head
density_residential_units
nodes_households_400m
nodes_post2000_du_3000m
nodes_jobs_3000m_agg4
ln_residential_units
median_sector_id
nodes_jobs_5000m_92
nodes_jobs_1500m_81
nodes_households_25km
std_age_of_head
prop_race_of_head_8
prop_race_of_head_9
median_tenure
nodes_households_35km
nodes_jobs_1500m_agg2
prop_race_of_head_2
prop_year_built_1975
mean_children
prop_race_of_head_1
prop_race_of_head_6
vacant_job_spaces
nodes_ave_year_built_800m
nodes_own_multifam_du_3000m
prop_sector_id_81
nodes_jobs_3000m_11
std_race_of_head
prop_sector_id_3133
sum_children
density_jobs
nodes_households_3000m
nodes_post2010_du_800m
nodes_jobs_1500m_3133
std_building_type_id
std_income
mean_tenure
nodes_jobs_1500m_11
nodes_ave_age_of_head_1500m
prop_workers_3
nodes_jobs_20km
nodes_jobs_3000m_42
nodes_rnt_multifam_du_800m
median_building_type_id
sum_persons
mean_building_type_id
total_jobs
std_sector_id
nodes_own_multifam_du_1500m
nodes_jobs_1500m_53
nodes_households_5000m
mean_sector_id
households
nodes_jobs_5000m_3133
nodes_jobs_25km
nodes_jobs_5000m_11
median_workers
mean_race_of_head
nodes_ave_income_3000m
nodes_jobs_3000m_21
nodes_jobs_3000m_23
nodes_jobs_3000m_22
median_cars
nodes_jobs_1500m_22
nodes_jobs_1500m_23
nodes_jobs_1500m_21
nodes_population_400m
z_id
nodes_households_20km
nodes_ave_year_built_1500m
prop_sector_id_22
prop_sector_id_23
job_spaces
sum_recent_mover
nodes_jobs_10km
nodes_own_singlfam_du_800m
median_age_of_head
prop_persons_7
nodes_households_1500m
prop_sector_id_54
total_residential_units
nodes_rnt_singlfam_du_1500m
nodes_jobs_3000m
prop_year_built_1955
prop_children_2
prop_persons_4
nodes_jobs_5000m_62
nodes_post2000_du_5000m
vacant_du_spaces
nodes_jobs_5000m_agg2
nodes_jobs_5000m_agg3
nodes_jobs_5000m_agg0
nodes_jobs_5000m_agg1
nodes_high_income_hh_3000m
nodes_jobs_5000m_agg4
nodes_jobs_5000m_agg5
prop_recent_mover_1
prop_recent_mover_0
own_multifam_post2010
prop_persons_1
std_cars
mean_persons
nodes_jobs_1500m_56
nodes_jobs_1500m_55
nodes_jobs_800m
nodes_jobs_3000m_4849
nodes_jobs_1500m_52
nodes_jobs_1500m_51
prop_sector_id_55
prop_persons_6
vacant_residential_units
prop_sector_id_56
prop_sector_id_51
prop_persons_2
prop_sector_id_53
prop_sector_id_52
nodes_high_income_hh_1500m
rnt_singlfam_post2010
prop_sector_id_4849
nodes_rnt_singlfam_du_800m
own_singlfam_post2010
sum_workers
prop_year_built_1945
prop_aggr_sector_id_3
prop_tenure_1
prop_aggr_sector_id_1
nodes_jobs_5000m_71
prop_aggr_sector_id_4
nodes_low_income_hh_3000m
nodes_jobs_20km_agg3
nodes_jobs_20km_agg2
nodes_jobs_20km_agg1
nodes_jobs_20km_agg0
nodes_jobs_20km_agg5
nodes_jobs_20km_agg4
nodes_jobs_3000m_54
nodes_jobs_3000m_55
mode_res_building_type
std_children
nodes_du_5000m
nodes_jobs_3000m_51
nodes_jobs_3000m_52
nodes_jobs_3000m_53
nodes_jobs_3000m_agg2
nodes_jobs_3000m_agg5
nodes_jobs_3000m_agg0
nodes_jobs_3000m_agg1
nodes_jobs_1500m_42
nodes_jobs_3000m_agg3
prop_sector_id_4445
prop_sector_id_42
nodes_jobs_40km
std_persons
prop_aggr_sector_id_2
nodes_jobs_5000m_4445
std_recent_mover
nodes_jobs_35km
nodes_population_1500m
nodes_rnt_singlfam_du_3000m
residential_units
res_btype_mode2
prop_children_0
prop_building_type_id_4
prop_building_type_id_1
nodes_households_40km
prop_building_type_id_3
prop_building_type_id_2
prop_year_built_1930
nodes_own_multifam_du_800m
res_btype_mode3
nodes_du_1500m
nodes_ave_year_built_3000m
nodes_jobs_15km
nodes_rnt_multifam_du_3000m
nodes_jobs_5000m_42
nodes_ave_income_1500m

In [5]:
households = orca.get_table('households').to_frame()

In [7]:
jobs = orca.get_table('jobs').to_frame()

In [10]:
residential_units = orca.get_table('residential_units').to_frame()

In [11]:
residential_units

,year_built,building_type_id,zone_id,y,x,node_id
du_id,,,,,,
1,1985,1,2700300000093,45.211345,-93.352016,2700300000093
2,1985,1,2700300000093,45.211345,-93.352016,2700300000093
3,1985,1,2700300000093,45.211345,-93.352016,2700300000093
4,1945,1,2700300000093,45.211345,-93.352016,2700300000093
5,1955,1,2700300000093,45.211345,-93.352016,2700300000093
6,1955,1,2700300000093,45.211345,-93.352016,2700300000093
7,1955,1,2700300000093,45.211345,-93.352016,2700300000093
8,1955,1,2700300000093,45.211345,-93.352016,2700300000093
9,1955,1,2700300000093,45.211345,-93.352016,2700300000093
10,1955,1,2700300000093,45.211345,-93.352016,2700300000093
11,1955,1,2700300000093,45.211345,-93.352016,2700300000093
12,1955,1,2700300000093,45.211345,-93.352016,2700300000093
13,1955,1,2700300000093,45.211345,-93.352016,2700300000093
14,1965,1,2700300000093,45.211345,-93.352016,2700300000093
15,1965,1,2700300000093,45.211345,-93.352016,2700300000093
16,1965,1,2700300000093,45.211345,-93.352016,2700300000093
17,1965,1,2700300000093,45.211345,-93.352016,2700300000093
18,1965,1,2700300000093,45.211345,-93.352016,2700300000093
19,1965,1,2700300000093,45.211345,-93.352016,2700300000093
20,1965,1,2700300000093,45.211345,-93.352016,2700300000093
21,1965,1,2700300000093,45.211345,-93.352016,2700300000093
22,1965,1,2700300000093,45.211345,-93.352016,2700300000093
23,1965,1,2700300000093,45.211345,-93.352016,2700300000093
24,1965,1,2700300000093,45.211345,-93.352016,2700300000093
25,1965,1,2700300000093,45.211345,-93.352016,2700300000093
26,1965,1,2700300000093,45.211345,-93.352016,2700300000093
27,1965,1,2700300000093,45.211345,-93.352016,2700300000093
28,1965,1,2700300000093,45.211345,-93.352016,2700300000093
29,1965,1,2700300000093,45.211345,-93.352016,2700300000093
30,1965,1,2700300000093,45.211345,-93.352016,2700300000093
...,...,...,...,...,...,...
1186957,2005,1,2716300000117,44.896816,-92.889297,2716300000117
1186958,2005,1,2716300000117,44.896816,-92.889297,2716300000117
1186959,2005,1,2716300000117,44.896816,-92.889297,2716300000117
1186960,2005,1,2716300000117,44.896816,-92.889297,2716300000117
1186961,2005,1,2716300000117,44.896816,-92.889297,2716300000117
1186962,2005,1,2716300000116,44.912975,-92.890180,2716300000116
1186963,2005,1,2716300000116,44.912975,-92.890180,2716300000116
1186964,2005,1,2716300000116,44.912975,-92.890180,2716300000116
1186965,1985,4,2716300000116,44.912975,-92.890180,2716300000116
1186966,2005,4,2716300000116,44.912975,-92.890180,2716300000116
1186967,1995,3,2716300000116,44.912975,-92.890180,2716300000116
1186968,1995,3,2716300000116,44.912975,-92.890180,2716300000116
1186969,2005,3,2716300000116,44.912975,-92.890180,2716300000116
1186970,2005,3,2716300000116,44.912975,-92.890180,2716300000116
1186971,2005,3,2716300000116,44.912975,-92.890180,2716300000116
1186972,2005,3,2716300000116,44.912975,-92.890180,2716300000116
1186973,2005,3,2716300000116,44.912975,-92.890180,2716300000116
1186974,2005,3,2716300000116,44.912975,-92.890180,2716300000116
1186975,2005,3,2716300000116,44.912975,-92.890180,2716300000116
1186976,2005,1,2716300000117,44.896816,-92.889297,2716300000117
1186977,2005,1,2716300000117,44.896816,-92.889297,2716300000117
1186978,2005,4,2716300000117,44.896816,-92.889297,2716300000117
1186979,2005,4,2716300000117,44.896816,-92.889297,2716300000117
1186980,1995,3,2716300000117,44.896816,-92.889297,2716300000117
1186981,2005,3,2716300000117,44.896816,-92.889297,2716300000117
1186982,2005,3,2716300000117,44.896816,-92.889297,2716300000117
1186983,2005,3,2716300000117,44.896816,-92.889297,2716300000117
1186984,2005,3,2716300000117,44.896816,-92.889297,2716300000117
1186985,2005,3,2716300000117,44.896816,-92.889297,2716300000117
1186986,2005,3,2716300000117,44.896816,-92.889297,2716300000117